### PR TITLE
Feature/appcli 45 create command upgrade as an alias of the migrate command

### PR DESCRIPTION
**Pull request by glen-wiltshire-bsl**

### CODE REVIEW

**Review by thomas-anderson-bsl — CHANGES_REQUESTED** [review]
This one is on me Glen and I apologise in advance for the miscommunications - we don't want `upgrade` or `migrate` to supersede the other. Neither command is deprecated or preferred, we just want an alias.

As such, could you please revert the changes to do with documentation / testing / renaming 'migrate' to 'upgrade', and the sole change to be adding the alias to 'upgrade/migrate' please? Neither command should be hidden either.

I'll discuss reasoning with you over VTC.

**Comment by glen-wiltshire-bsl** [comment]
Changes reverted, options for "update" and "migrate" now both exist (both do the same thing). 
The documentation should be changed with this but I'll need to wait to see the results of #45 before doing so.

**Review by thomas-anderson-bsl — APPROVED** [review]
Approved.

**Comment by thomas-anderson-bsl** [comment]
resolves #35

**Pull request merged**
